[package]
name = "exclusive-range-map"
version = "1.0.0-alpha"
edition = "2024"
authors = ["Savanna H Evens <sevens@sevensprojects.net>"]
description = "Map that uses exclusive, non-overlapping ranges as keys to arbitrary data"
license = "MIT OR Apache-2.0"

[dependencies]
